name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger only when a version tag like v1.0.0 is pushed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Change as needed

      - name: Create release archive
        run: |
          mkdir dist
          zip -r dist/SEC.zip src requirements.txt data ReadMe.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/SEC.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
